### ISSUE TITLE
Inclusion of trailing separator in base URL

### ISSUE THREAD

**Issue by jd-au** [ivoa-std/SSA#4]
There is confusion between the examples and the normative text of the standard as to whether the trailing separator should be included in the registered base URL for an SSA service. The last character of the base URL could be either a question mark '?' or an ampersand '&' depending on whether the service is defined with extra query parameters.

It has been common practice to include the trailing separator in the registered base URL. 

Affected sections are: 3.2, 8.3.3 and 8.10

Raised in https://wiki.ivoa.net/internal/IVOA/InterOpMay2021Ops/dalissues.pdf

**Comment by jd-au** [comment]
Draft erratum at https://wiki.ivoa.net/twiki/bin/view/IVOA/SSA-1_1-Err-1

**Comment by mbtaylor** [comment]
@jd-au, I mostly agree with the erratum text, but I'd suggest a bit more adjustment to the corrected example from Section 8.3.3. That single line in the original SSA 1.1 reads:
```
http://host:port]/path[?[name[=value]{&name=[value]}]]
```
which is jam-packed with mistakes and anomalies:
* missing `[` before `:port]`
* why `name[=value]` in one place and `name=[value]` in the other?

as well as the issue we're trying to fix here.

Although I agree we should try to keep this Erratum focussed on the issue at hand, since we're touching this line anyway I think we'd be justified in fixing it to actually make sense, so I'd suggest to replace it with:
```
http://host[:port]/path?{name[=value]&}
```
which I think says what we're trying to convey here (do you agree?) as succinctly as possible.  I'm not sure about making `=value` (or should it be `value`?) optional, but since it's there already better not remove it.

Then there should also be a comment either in the Rationale or near the 8.3.3 replaced text along the lines "This also fixes some unrelated errors in the original example".

Happy to hear alternative opinions...

**Comment by molinaro-m** [comment]
I agree with @mbtaylor on the proposed replacement and the note on fixing all the example issues.

I'd also add a sentence in the **impact assessment** directly related to validators, so that a missing trailing _"?"_ doesn't stop the validation process but let the error be report and the validation process continue.
This should close the loop this erratum starts from.

**Comment by jd-au** [comment]
Thanks @mbtaylor  and @molinaro-m , I have made the suggested changes.

**Comment by molinaro-m** [comment]
Fine for me. Thanks @jd-au!

**Comment by mbtaylor** [comment]
I fixed a couple of typos on the wiki ("trialing"->"trailing" twice); other than that looks good to me, thanks.

**Comment by jd-au** [comment]
Resolved in erratum 1 and now applied to the SSA.doc in PR #7
